### ISSUE TITLE
GO binaries haven't been added to the release

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#67]
The build binaries of the FortigateExporter have not been added to the Release.

**Comment by bluecmd** [comment]
```
[10:08:17 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository bluecmd/fortigate_exporter.

[10:08:17 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository bluecmd/fortigate_exporter.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:96:17)
        at verifyConditions (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/node_modules/@semantic-release/github/index.js:27:9)
        at validator (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)
    at /home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/index.js:95:3)
    at async module.exports (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/.npm/_npx/6828/lib/node_modules/semantic-release/cli.js:55:5)
```

I will create the token

**Comment by bluecmd** [comment]
```
[10:31:40 PM] [semantic-release] [@semantic-release/github] › ✖  The asset target/fortigate-exporter.darwin.amd64 cannot be read, and will be ignored.
[10:31:40 PM] [semantic-release] [@semantic-release/github] › ✖  The asset target/fortigate-exporter.windows.amd64.exe cannot be read, and will be ignored.
[10:31:40 PM] [semantic-release] [@semantic-release/github] › ✖  The asset target/fortigate-exporter.linux.amd64 cannot be read, and will be ignored.
```

**Comment by bluecmd** [comment]
@secustor I'll let you fix that one, you seems to have your 👀 on it ;-).
